SI = main
SRC = main.cpp

OBJECT = $(SRC:.cpp=.o)

CC = c++
CPPFLAGS = -Wall -Wextra -Werror -std=c++98

all : $(SI)
$(SI): $(OBJECT)	$(CC) $(CPPFLAGS) $(OBJECT) -o $(SI)
clean:
	rm -rf $(OBJECT)

fclean: clean
	rm -rf $(SI)
re: fclean all

.PHONY: all clean fclean re	
